# Generated by Django 6.1 on 2026-08-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='priority_support',
            field=models.BooleanField(default=False),
        ),
    ]
